server:
  port: 8080
  servlet:
    #  全局路径配置
    context-path: /sail
spring:
  application:
    name: sail
  datasource:
    url: jdbc:mysql://localhost:3306/sail?serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: xp14459048

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coatardbul.sail.model.entity

logging:
  path: logs/
  level:
    com.coatardbul.sail.feign.*: debug
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug