spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sail?serverTimezone=GMT&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: xp14459048
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coatardbul.sail.model.entity
  #sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug
#  path: logs/
#  file: %d{yyyy-MM-dd}.log
#    max-size: 1GB

#全局路径配置
#server:
#  servlet:
#    context-path: /bedc

